version: '3.3'
services:
  redis:
    image: redis
    volumes:
      - redis:/data
    expose:
      - 6379

  app:
    environment:
      - SECRET=YOUR_SECRET_HERE
      - REDIS_HOST=redis://redis
      - REDIS_PORT=6379
    restart: always
    depends_on:
      - redisdb
    image: baspla/ehren_bank
volumes:
  redis: