name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v3
    - name: Using Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - name: npm build
      run: |
          npm install
          npm run build --if-present
    - name: Docker Login
      env:
        DOCKER_USER: ${{ github.actor }}
        DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Docker Build
      run: docker build . --file Dockerfile --tag dockerShare/ehren_bank:latest
    - name: Docker Push
      run: docker push dockerShare/ehren_bank
